### ISSUE TITLE
Section 2 -step 4 - You don't need to modify the script 

### ISSUE THREAD

**Issue by LarsIpsen** [ibm-cloud-docs/security-compliance#14]
In Section 2 :  Create and install a collector ,  Step 4 : "Transfer the collector installation ....."
Bullet 4 says :"Paste the content that you previously copied."

But there is no previously step that copy the content, and I doubt, that you need to modify the script, at least it seems to work for me without any modifications. So the the section can be simplified.

Btw, it can be an good idea to inform that you can transfer the file with scp or similar commands

**Comment by smguilia** [comment]
I've forwarded this feedback to our development team. There is an internal issue where he is working through testing. Since there is an internal issue, I will close this one and reach out on Slack with any updates.

Thanks for opening the feedback! Please don't hesitate to reach out in the future if you come across other areas that can be simplified.

- Shawna
